### ISSUE TITLE
ServerAuth v1.11 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerAuth#14]
ServerAuth v1.11 upcoming features:
- [x] Fix automatic language files saving not working on Unix based OS
- [x] Fix register with password confirmation message not working
- [x] Add missing _serverauth.help_ permission on _plugin.yml_ file

**Comment by Flavius12** [comment]
Done! :D
