### ISSUE TITLE
 ServerAuth v3.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerAuth#142]
ServerAuth v3.0 upcoming features __(The BIGGEST ServerAuth update you've ever seen!)__:
- [x] API Bump to 3.0.0-ALPHA12
- [x] Multi-hash password support (supports salted hash and SimpleAuth default hash algorithm)
- [x] More flexible API to highly customize almost all ServerAuth aspects
- [x] Data provider system
- [x] SQLite3 data provider
- [x] Exchange ServerAuth data between providers (such as ServerAuth YAML data -> ServerAuth MySQL data...)
- [x] Import data from other auth plugins (such as SimpleAuth, HereAuth...)
- [x] User cache (highly improves plugin performance)
- [x] Better error codes
- [ ] Update language files
- [x] Add Turkish language (thanks to @Gecekatili for translation)
- [x] Customizable auth commands (such as /register, /login...)
- [x] Custom message handlers
- [x] Improve code logic and syntax
- [x] Improve ServerAuth events
- [x] UUID support
- [ ] [Cancelled] Log players with multiple accounts
- [x] Reimplement max registrations per IP

ServerAuthWebAPI v3.0 upcoming features:

- [x] ServerAuth API bump
- [x] Data provider system

ServerAuth Account Manager v2.0:

- [ ] ServerAuth API bump

**Comment by daniktheboss** [comment]
question: Why use this when we have xbox auth?

**Comment by Flavius12** [comment]
I had got the same question but lot of people told me that there are servers in which you can play without xbox authentication. There are also some MCPE custom launchers which allows to bypass xbox auth as well.

**Comment by Aericio** [comment]
Welcome back to PocketMine, I guess. Excited to use this plugin again, after a year :P

**Comment by Flavius12** [comment]
The plugin is useless since Xbox Auth is always required. No update will be released officially.
