### ISSUE TITLE
ServerAuth v2.00 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerAuth#26]
ServerAuth v2.00 upcoming features:
- [x] Fix bugs on server reload (MessageTask.php)
- [x] Update database data on plugin reload
- [x] Implement cancellable events
- [x] Allow player unregistration from console
- [x] Block player joining with the same username when the player is authenticated
- [x] Block EntityDamageEvent for not authenticated/registered users
- [x] Fix logout
- [x] Fixed permissions for /serverauth command (Thanks to @Pub4Game)
- [x] Fixed a /give command related bug (Thanks to @Pub4Game)
- [x] Kick players after n° of failed login attempts feature

**Comment by Flavius12** [comment]
Done!
