### ISSUE TITLE
ServerAuth v2.12 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerAuth#37]
ServerAuth v2.12 Upcoming Features:
- [x] Customizable no-permissions and player-only-command strings (in languages)
- [x] Issue #33 possible fix
- [x] Possible blocking of crafting for non authenticated players (#35)
- [x] Add operation cancelled message on _ChangePassword.php_ command
- [x] Possible help command with language support
- [x] Add SQL Injection protection in ServerAuthWebAPI (issue #47)
- [x] Performance Improvements (Thanks to @legoboy0215 and @PEMapModder)
- [ ] Possible SQLite Support

**Comment by Flavius12** [comment]
Done! :D
