### ISSUE TITLE
ServerAuth v1.10 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerAuth#6]
ServerAuth v1.10 upcoming features:
- [x] Check and block all events
- [x] Automatic default languages saving
- [x] Limit number of registrations for IP

**Comment by Flavius12** [comment]
Done! :D
